name: publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bravesdevs1/allmaps:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t bravesdevs1/allmaps .
          docker push bravesdevs1/allmaps:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Removing allmaps container if exists
        run: docker rm -f allmaps || true

      - name: Pull Image
        run: docker pull bravesdevs1/allmaps:latest

      - name: Run Container
        run: docker run -d -p 3000:3000 --name allmaps \
          -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
          -e GEMINI_MODEL=${{ secrets.GEMINI_MODEL }} \
          -e MODEL_PROMPT=${{ secrets.MODEL_PROMPT }} \
          -e SAFETY_SETTINGS=${{ secrets.SAFETY_SETTINGS }} \
          -e GENERATION_CONFIG=${{ secrets.GENERATION_CONFIG }} \
          bravesdevs1/allmaps:latest
