name: publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bravesdevs1/allmaps:latest

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t bravesdevs1/allmaps .
          docker push bravesdevs1/allmaps:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ip-172-31-6-134]

    steps:
      - name: Pull Image
        run: |
          docker pull bravesdevs1/allmaps:latest
      - name: Revising Container
        run: |
          docker stop allmaps
          docker rm allmaps
          docker run -d -p 3000:3000 --name allmaps bravesdevs1/allmaps:latest
