name: publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bravesdevs1/allmaps:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t bravesdevs1/allmaps .
          docker push bravesdevs1/allmaps:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [allmaps_runner]

    steps:
      - uses: actions/checkout@v3
      - name: Pull Image
        run: |
          docker pull docker.io/bravesdevs1/allmaps:latest
      - name: Revising Container
        run: |
          docker rm -f allmaps
          docker run -d -p 3000:3000 --name allmaps allmaps:latest
