name: publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bravesdevs/allmaps:latest

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Docker login
        run: docker login ghcr.io -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t bravesdevs/allmaps .
          docker push bravesdevs/allmaps:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ip-172-31-6-134]

    steps:
      - name: Pull Image
        run: |
          docker pull bravesdevs/allmaps:latest
      - name: Revising Container
        run: |
          docker stop allmaps
          docker rm allmaps
          docker run -d -p 3000:3000 --name allmaps bravesdevs/allmaps:latest
