name: publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bravesdevs1/allmaps:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t bravesdevs1/allmaps .
          docker push bravesdevs1/allmaps:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Removing allmaps container if exists
        run: docker rm -f allmaps

      - name: Pull Image
        run: docker pull bravesdevs1/allmaps:latest

      - name: Run Container
        run: docker run -d -p 3000:3000 --name allmaps bravesdevs1/allmaps:latest
